---
name: Darglint

on:
  push:
    branches:
      - master
      - dev
  pull_request:
        branches: [master, dev]

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Run Tests
      run: |
        bash scripts/ci_darglint.sh
